spring:
  datasource:
    url: jdbc:postgresql://193.124.15.94:5432/mydb
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop


#springdoc:
#  swagger-ui:
#    path: /swagger-ui
#  api-docs:
#    path: /v3/api-docs