spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

jwt:
  secret-key: ${JWT_SECRET}
  validity: ${JWT_VALIDITY}


springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs