spring:
  datasource:
    url: jdbc:postgresql://193.124.15.94:5432/mydb
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

jwt:
  secret-key: gdyw7h32e87732h1jbdbchd273dh2bds7dad3h2j1d78
  validity: 36000000


springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /v3/api-docs